name: 'Hello World'
description: 'Greet someone'
inputs:
  check-file:
    description: "HTML File to check for spelling mistakes."
    required: true

runs:
  using: "composite"
  steps:
    - run: echo ${{ inputs.check-file }}
      shell: bash
