name: 'Hello World'
description: 'Greet someone'
inputs:
  check-file:
    description: "HTML File to check for spelling mistakes."
    required: true

runs:
  using: "composite"
  steps:
    - run: cat ${{inputs.check-file}} | aspell list --mode=html | sort --unique
      shell: bash
