name: 'Hello World'
description: 'Greet someone'
inputs:
  check-file:
    description: "HTML File to check for spelling mistakes."
    required: true
  ignore-file:
    description: "Newline-separated file containing words to ignore."
    required: true

runs:
  using: "composite"
  steps:
    - run: |
        diff=$(comm -23 <(cat ${{inputs.check-file}} | aspell list --mode=html | sort --unique) <(sort --unique ${{inputs.ignore-file}}))
        if [[ $diff ]]; then
          echo "Spelling mistakes detected!"
          echo "---------------------------"
          echo $diff
          echo "---------------------------"
          exit 1
        else
          exit 0
        fi
      shell: bash
